development:
  password: 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
  theme_id: "117136097434"
  store: jackspremium.myshopify.com
  ignore:
  - config/settings_data.json
  - assets/scripts/*
  - assets/styles/*

production:
  password: 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
  theme_id: "117136195738"
  store: jackspremium.myshopify.com
  ignore:
  - config/settings_data.json

